### ISSUE TITLE
Problem with NO-PIE Binaries

### ISSUE THREAD

**Issue by jfma7** [arget13/DDexec#1]
Hello:

After testing the tool I noticed that it does not respond correctly with binaries generated by msfvenom (and probably with some others).

![image](https://user-images.githubusercontent.com/38380929/158018058-8c4c9968-1b3e-4dcf-b71b-7efef07bf0df.png)

As we discussed by mail, one of the errors was due to the .bss section but after fixing that bug, it still responds incorrectly. 

I am still investigating why this is happening.

Regards,
J.

**Comment by arget13** [comment]
Yup, I have seen that in fact I have a really big bug when dealing with non-PIE binaries. My script simply is ignoring the case that a binary may not be PIE. The problem resides specifically in the `if` on line 205.
```sh
    if [ $entry -lt $((0x400000)) ] # For PIE binaries
    then
        if [ $1 = "bin" ]
        then
            base=$((0x400000))
        else
            base=$((0x$3))
        fi

        entry=$(endian $(printf %016x $((entry + base))))
    fi
```
The variable `base` is only set when the binary is PIE. I am working on it. Thank you.
