### ISSUE TITLE
Use "ld" to exec "dd" without file system's exec permission

### ISSUE THREAD

**Issue by fabianofurtado** [arget13/DDexec#10]
Hi...
As described in the README.md, making dd executable only by root WILL NOT prevent this technique being executed by the filesystem: you could call "ld" before calling "dd".
Please, add $loader variable to your script to use the "ld" and "dd" together.
Thanks in advance.

**Comment by arget13** [comment]
This is by default disabled. You can make `export USE_INTERP=1` and then run the script in order to use this technique.
