### ISSUE TITLE
Not work with google cloud shell

### ISSUE THREAD

**Issue by hugeintimate** [arget13/DDexec#12]
i use google cloud shell environment but it doesn't work

**Comment by hugeintimate** [comment]
![Uploading Screenshot_20230321_101223_Chrome.jpg…]()

**Comment by hugeintimate** [comment]
![Screenshot_20230321_101223_Chrome](https://user-images.githubusercontent.com/128444133/226509655-a765df0e-c97b-4817-9865-b1610d14cdae.jpg)

**Comment by arget13** [comment]
Hello, thank you for your feedback. That behaviour isn't due to an error or bug in DDexec, it's because that system is hardened against this technique and there's nothing else we can do!

**Comment by arget13** [comment]
What I would really like to learn is how they managed to make the mem file readonly.
![imagen](https://user-images.githubusercontent.com/44529046/226772718-ab40bccb-9ddb-4ba2-8bb3-23940d7c92b6.png)
