### ISSUE TITLE
Problem with static binaries

### ISSUE THREAD

**Issue by jfma7** [arget13/DDexec#4]
Hello:

I noticed that the ddexec.sh module does not work correctly with static binaries:

`Inconsistency detected by ld.so: rtld.c: 1619: dl_main: Assertion GL(dl_rtld_map).l_libname' failed!`

Regards

**Comment by arget13** [comment]
Hi, this happens because we should not call the linker when the file is static,
I am working on it.
In theory I have already fixed it, but sometimes it just loops forever.
